development:
  adapter: mysql2
  encoding: utf8
  database: image_sharing_development
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  database: image_sharing_production
  username: root
  password: root